require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/local_resources", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # LocalResource. As you add validations to LocalResource, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      LocalResource.create! valid_attributes
      get local_resources_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      local_resource = LocalResource.create! valid_attributes
      get local_resource_url(local_resource)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_local_resource_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      local_resource = LocalResource.create! valid_attributes
      get edit_local_resource_url(local_resource)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new LocalResource" do
        expect {
          post local_resources_url, params: { local_resource: valid_attributes }
        }.to change(LocalResource, :count).by(1)
      end

      it "redirects to the created local_resource" do
        post local_resources_url, params: { local_resource: valid_attributes }
        expect(response).to redirect_to(local_resource_url(LocalResource.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new LocalResource" do
        expect {
          post local_resources_url, params: { local_resource: invalid_attributes }
        }.to change(LocalResource, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post local_resources_url, params: { local_resource: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested local_resource" do
        local_resource = LocalResource.create! valid_attributes
        patch local_resource_url(local_resource), params: { local_resource: new_attributes }
        local_resource.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the local_resource" do
        local_resource = LocalResource.create! valid_attributes
        patch local_resource_url(local_resource), params: { local_resource: new_attributes }
        local_resource.reload
        expect(response).to redirect_to(local_resource_url(local_resource))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        local_resource = LocalResource.create! valid_attributes
        patch local_resource_url(local_resource), params: { local_resource: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested local_resource" do
      local_resource = LocalResource.create! valid_attributes
      expect {
        delete local_resource_url(local_resource)
      }.to change(LocalResource, :count).by(-1)
    end

    it "redirects to the local_resources list" do
      local_resource = LocalResource.create! valid_attributes
      delete local_resource_url(local_resource)
      expect(response).to redirect_to(local_resources_url)
    end
  end
end
